SuperHerosProject/SuperHerosProject/urls.py
from django.urls import path, include
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('SuperHerosapp/', include('SuperHerosapp.urls')),
    path('', RedirectView.as_view(url='/SuperHerosapp/'))
]

SuperHerosProject/SuperHerosapp/urls.py
from . import views
from django.urls import path


app_name = 'SuperHerosapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<int:superhero_id>', views.detail, name='detail'),
    path('new/', views.create, name='create'),
    path('change/<int:superhero_id>', views.change, name='change'),
    path('delete/<int:superhero_id>', views.delete, name='delete')
]

SuperHerosProject/SuperHerosapp/models.py
from django.db import models


# Create your models here.
class Superhero(models.Model):
    name = models.CharField(max_length=50)
    alter_ego = models.CharField(max_length=50)
    primary_ability = models.CharField(max_length=50)
    secondary_ability = models.CharField(max_length=50)
    catchphrase = models.CharField(max_length=50)

    def __str__(self):
        return self.name, self.alter_ego, self.primary_ability, self.secondary_ability, self.catchphrase

SuperHerosProject/SuperHerosapp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Superhero
# Create your views here.


def index(request):
    all_superheroes = Superhero.objects.all()
    context = {
        'all_superheroes': all_superheroes
    }
    return render(request, 'SuperHerosapp/index.html', context)

def detail(request, superhero_id):
    specific_superhero = Superhero.objects.get(pk=superhero_id)
    context = {
        'specific_superhero': specific_superhero
    }
    return render(request, 'SuperHerosapp/detail.html', context)

def change(request, superhero_id):
    specific_superhero = Superhero.objects.get(pk=superhero_id)
    context = {
        'specific_superhero': specific_superhero
    }
    if request.method == 'POST':
        change_name = request.POST.get('change_name')
        change_alter_ego = request.POST.get('change_alter_ego')
        change_primary_ability = request.POST.get('change_primary_ability')
        change_secondary_ability = request.POST.get('change_secondary_ability')
        change_catchphrase = request.POST.get('change_catchphrase')
        superhero_id = Superhero(name=change_name, alter_ego=change_alter_ego, primary_ability=change_primary_ability, secondary_ability=change_secondary_ability, catchphrase=change_catchphrase)
        superhero_id.save()
        return HttpResponseRedirect(reverse('SuperHerosapp:detail', context))
    else:
        return render(request, 'SuperHerosapp/change.html', context)

def create(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        alter_ego = request.POST.get('alter_ego')
        primary_ability = request.POST.get('primary_ability')
        secondary_ability = request.POST.get('secondary_ability')
        catchphrase = request.POST.get('catchphrase')
        new_superhero = Superhero(name=name, alter_ego=alter_ego, primary_ability=primary_ability, secondary_ability=secondary_ability, catchphrase=catchphrase)
        new_superhero.save()
        return HttpResponseRedirect(reverse('SuperHerosapp:index'))
    else:
        return render(request, 'SuperHerosapp/create.html')


def delete(request, superhero_id):
    delete_superhero = Superhero.objects.get(pk=superhero_id)
    Superhero.delete(delete_superhero)
    return HttpResponseRedirect(reverse('SuperHerosapp:index'))

SuperHerosProject/SuperHerosapp/templates/SuperHerosapp/change.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Modify {{superhero.name}}</title>
</head>
<body>
   <form action="{% url 'SuperHerosapp:change' specific_superhero.id %}" method="post">
    {% csrf_token %}
    Change Name:<input type="text" name="name" id="name"><br>
    Change Alter Ego:<input type="text" name="alter_ego" id="alter_ego"><br>
    Change Primary Ability:<input type="text" name="primary_ability" id="primary_ability"><br>
    Change Secondary Ability:<input type="text" name="secondary_ability" id="secondary_ability"><br>
    Change Catchphrase:<input type="text" name="catchphrase" id="catchphrase"><br>
    <input type="submit" value="Save">
  </form>
</body>
</html>

SuperHerosProject/SuperHerosapp/templates/SuperHerosapp/create.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>New Meta-Human Entry</title>
</head>
<body>
  <form action="{% url 'SuperHerosapp:create' %}" method="post">
    {% csrf_token %}
    Name:<input type="text" name="name" id="name"><br>
    Alter Ego:<input type="text" name="alter_ego" id="alter_ego"><br>
    Primary Ability:<input type="text" name="primary_ability" id="primary_ability"><br>
    Secondary Ability:<input type="text" name="secondary_ability" id="secondary_ability"><br>
    Catchphrase:<input type="text" name="catchphrase" id="catchphrase"><br>
    <input type="submit" value="Save">
  </form>
</body>
</html>

SuperHerosProject/SuperHerosapp/templates/SuperHerosapp/detail.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
     {% load static %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <title>{{specific_superhero.name}}</title>
</head>
<body>
    <h1>{{specific_superhero.name}} Details</h1>
    <ul>
        {% if specific_superhero %}
        <li><h2>Alter Ego: {{specific_superhero.alter_ego}}</h2></li>
        <li><h2>Primary Ability: {{specific_superhero.primary_ability}}</h2></li>
        <li><h2>Secondary Ability: {{specific_superhero.secondary_ability}}</h2></li>
        <li><h2>Catchphrase: "{{specific_superhero.catchphrase}}"</h2></li>
        {% endif %}
    </ul>
        <a href="{% url 'SuperHerosapp:index' %}">Cerebro's Main Menu</a>
</body>
</html>

SuperHerosProject/SuperHerosapp/templates/SuperHerosapp/index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Superheroes Index</title>
</head>
<body>
    <h1>Superheros</h1>
        <ul>
            {% for superhero in all_superheroes %}
            <li><h2>{{superhero.name}}</h2></li>
            <li><a href="{% url 'SuperHerosapp:detail' superhero.id %}">See more info</a></li>
            <li><a href="{% url 'SuperHerosapp:change' superhero.id %}">Change Details Here</a></li>
            <li><a href="{% url 'SuperHerosapp:delete' superhero.id %}">Delete</a></li>
            {% endfor %}
        </ul>
    <a href="{% url 'SuperHerosapp:create' %}">Add a New Meta-Human to Cerebro's database</a>
</body>
</html>